### ISSUE TITLE
Can it run?

### ISSUE THREAD

**Issue by NetworkG** [TeamHorizon/vendor_xenonhd#10]
Can this rom run on goclever T76 GPS? (sorry if this is in wrong place)

TeleChips 8925 Cortex A5 1GHz
512mb RAM 
Mali-400 MP

**Comment by NetworkG** [comment]
seriously help

**Comment by MiguelNdeCarvalho** [comment]
Hey,
First of all you need to have device trees to build a ROM for that device. Second point the phone that you are referring have such a low hardware, I think it can´t.
Thanks,
Miguel de Carvalho
