### ISSUE TITLE
Locate internal audio folder

### ISSUE THREAD

**Issue by Echolon** [TeamHorizon/vendor_xenonhd#11]
Hi,

normally the internal audio file of android can be found here:

/system/media/audio/ui
(I was looking for lock.ogg and unlock.ogg)

For my HTC Once M7 unfortunately I could find _any_ file in there. Have you changed somehting about it?

Used TWRP to access the folders.

Cheers & thanks for your work!

**Comment by danparidae** [comment]
Hey, all sounds are being stored in /system/media/audio like you correctly said. I guess you probably didn't mount /system in TWRP and that's why it's empty. BTW here is the easier way to get the sounds we use - https://github.com/TeamHorizon/frameworks_base/tree/p/data/sounds/material

**Comment by Echolon** [comment]
Thanks guys, worked!

> I guess you probably didn't mount /system in TWRP and that's why it's empty.  

Guilty :smile_cat:
