### ISSUE TITLE
Clock and Snooze is not working

### ISSUE THREAD

**Issue by Echolon** [TeamHorizon/vendor_xenonhd#13]
Hello,

after the last Xenon update my clock is not working properly anymore. For example cannot open the app at all. Clicking the notification bar clock does nothing.
Then I installed another clock app from Fdroid. That basically works, but swipe to snooze does not.

Xenon HD: 200609
HTC One M7

Did that happen to anyone else?

**Comment by ljjehl** [comment]
Will check it out and update mirrors

**Comment by Echolon** [comment]
I updated today anf if you changed someting - it is working again. So thank you very much!

**Comment by ljjehl** [comment]
I did, and you're welcome
