### ISSUE TITLE
Build 09-01-2020: Boot loop

### ISSUE THREAD

**Issue by Echolon** [TeamHorizon/vendor_xenonhd#14]
Hello guys,

I installed 09-01-2020 on my HTC One M7 - however it get stuck in a boot loop. Is there anything known?

I experienced that this seem to connect with or without the installation of superSU.

However, that didn't happened before :+1: 
Any ideas?

**Comment by danparidae** [comment]
@ljjehl

**Comment by ljjehl** [comment]
It might be a while before I can try to replicate the issue.  My M7 device is elsewhere and not in my hands at the moment.  If you are using SuperSU, It might be a better idea trying out Magisk this time.  SuperSU is outdated.

**Comment by Echolon** [comment]
Does not happen after the last release.

**Comment by ljjehl** [comment]
Thank you
