### ISSUE TITLE
Broken audio recordings

### ISSUE THREAD

**Issue by Echolon** [TeamHorizon/vendor_xenonhd#15]
My audio recordings are broken, independent which app (incl. simple recorder app) . Not that there is dirt or something in the microphone (I also connected my headphones and Bluetooth headset). Its a noise like you have no signal on TV (https://www.youtube.com/watch?v=fA7GZsJGYBg)

Has there been any changes regarding this? To me this "sounds" like a software issue.
 
Build: 20200708

Kind regards

**Comment by ljjehl** [comment]
As I said in the prior issues response, personal M7 device is currently not able to be obtained to test the issues you are experiencing.  I'll check it out soon and hopefully build an update with newer security with the fix if needed

**Comment by Echolon** [comment]
Thank you, take your time!

**Comment by Echolon** [comment]
Hi @ljjehl,

have you found sometime for reviews?

Best regards

**Comment by Echolon** [comment]
Somehow this seems to be gone ... I think my phone is just end of life.

**Comment by Echolon** [comment]
Ok, this still exists, but I dont know if the OS is the reason.

**Comment by ljjehl** [comment]
Can you give me a little more info?  What device variant?  What app are you using, built in or third party?

**Comment by Echolon** [comment]
@ljjehl Sorry, forgot to mention. Its a HTC One M7 international.
What ever build-in recording app or voice message I use, or different mircofone, there is this loud noise sound.

**Comment by ljjehl** [comment]
> @ljjehl Sorry, forgot to mention. Its a HTC One M7 international.
> What ever build-in recording app or voice message I use, or different mircofone, there is this loud noise sound.

Another way is to try talking with someone in a voice call.  If someone has an issue hearing you (static and feedback), then it just could possibly be the microphone shot.  Otherwise I'll check into some things in regards to libs and such in relation to the microphone as well apps.

**Comment by Echolon** [comment]
Thanks, yes I did so. Calls, voice messages. The recorded data is broken.

Maybe my microfone is also broken and nothing can help anymore.

Would be nice, but if thats too much work, I understand if you refuse

4 nov. 2020 2:21:47 PM ljjehl <notifications@github.com>:
