### ISSUE TITLE
Update XenonOTA doesn't work

### ISSUE THREAD

**Issue by Echolon** [TeamHorizon/vendor_xenonhd#9]
Hi,

when I downloaded the current XenonOTA file and expected it to install. Then I just clicked the Download ROM button again and the filemanager just navigated to the location. I guess I somehow use the wrong app to handle it. What can I change? Or how to reset it?

**Comment by danparidae** [comment]
What's your device and Android version?

**Comment by Echolon** [comment]
HTC One M7, Android 7.1.2

**Comment by danparidae** [comment]
our OTA app won't automatically flash the downloaded file on nougat. You need to flash it manually through recovery

**Comment by Echolon** [comment]
Okay, thanks, good to know!

**Comment by Echolon** [comment]
Where can I download best for HTC One M7?

**Comment by danparidae** [comment]
this is the latest build for M7 - https://mirrors.c0urier.net/android/teamhorizon/N/Official/m7/XenonHD-190417-Official-m7.zip

**Comment by Echolon** [comment]
Thank you very much!

Last question: Where can I donate for the project? :)

Cheers

**Comment by danparidae** [comment]
we don't have any official donations running, but you can always donate to maintainer of your device ;)

**Comment by Echolon** [comment]
Okay, who is it?

(Maybe you should :) )

**Comment by danparidae** [comment]
@ljjehl is your maintainer. his paypal email is ljjehl@gmail.com

**Comment by Echolon** [comment]
Thanks a lot!
